### ISSUE TITLE
Code breaks when XPOSTAG does not match with the mapping dict

### ISSUE THREAD

**Issue by himanshudce** [cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter#12]
code breaks when it get XPOSTAG which is not in this [mapping_dict](https://github.com/cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter/blob/2131fc85b01c41aed1762ab2fc652deaa486af53/cdliconll2conllu/mapping.json#L25) like [here](https://github.com/cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter/blob/2131fc85b01c41aed1762ab2fc652deaa486af53/resources/P1113472.conll#L9) the code breaks at line o.3.1, the output of the file is [this](https://github.com/cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter/blob/master/resources/output/P1113472.conll)

**Comment by epageperron** [comment]
We woud have to check if this has been added manually or using the pre-annotator. If it's the pre-annotator, then it should be modified to output something that will pass, if it's manually then the text should be excluded and this should be mentioned in the log. It's ok for the converter to expect valid files, but it also shouldn't stop working if a file is not valid.

**Comment by epageperron** [comment]
@himanshudce this will be solved with your next PR right?

**Comment by himanshudce** [comment]
Yes it is fixed and merged
