### ISSUE TITLE
Option to specify the output folder to save the converted files

### ISSUE THREAD

**Issue by thesagarsehgal** [cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter#4]
Currently, the output folder is created within the directory having the input files itself. 
We can have an option of `-o` i.e. `--output_folder`, where we can specify the folder where we want to save the converted file and the output file would be saved there. 
And if by chance the folder is the same folder as the folder containing input file or it is not mentioned, then it would do the same as it is doing currently, i.e. create an output folder at that place itself.

**Comment by thesagarsehgal** [comment]
Since the code has been merged, so can I close this issue?

**Comment by jayanthkmr** [comment]
yes closed.
