### ISSUE TITLE
split using tabs instead of spaces

### ISSUE THREAD

**Issue by thesagarsehgal** [cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter#6]
Since the words in the files are separated using tabs, we should also split the sentence using tabs only. But we have separated it using spaces [here](https://github.com/cdli-gh/CDLI-CoNLL-to-CoNLLU-Converter/blob/ed6ad4cc5f39745abdae6c276e2692d4fa6ab8ec/cdliconll2conllu/converter.py#L43). Should I update it to split it on the basis of `\t`.

**Comment by jayanthkmr** [comment]
Confirm this with lllya. The code looks ok.
